export const PRICING_PLANS = [
  {
    name: "Free",
    price: "$0",
    period: "/month",
    description: "Perfect for trying out EventKit with a single event.",
    features: [
      "1 event",
      "Up to 50 attendees",
      "Basic event website",
      "Email confirmations",
      "QR code check-in",
      "Community support",
    ],
    highlighted: false,
    cta: "Get Started",
    ctaHref: "/sign-up",
  },
  {
    name: "Pro",
    price: "$49",
    period: "/month",
    description: "Everything you need to run professional events at scale.",
    features: [
      "Unlimited events",
      "Unlimited attendees",
      "AI website generation",
      "AI email builder",
      "Custom badge designer",
      "Stripe payments (CAD)",
      "Custom registration forms",
      "Priority email support",
    ],
    highlighted: true,
    cta: "Start Free Trial",
    ctaHref: "/sign-up",
  },
  {
    name: "Enterprise",
    price: "Custom",
    description: "For organizations with advanced security and support needs.",
    features: [
      "Everything in Pro",
      "SSO / SAML authentication",
      "Dedicated account manager",
      "Custom integrations",
      "SLA guarantee",
      "Invoice billing",
      "Data export API",
      "On-premise option",
    ],
    highlighted: false,
    cta: "Contact Sales",
    ctaHref: "mailto:sales@eventkit.ca",
  },
] as const;
